# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- task: TerraformInstaller@0
  displayName: Terraform Installer
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  displayName: Terrform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure'
    backendAzureRmResourceGroupName: 'RG1'
    backendAzureRmStorageAccountName: 'saterraformb'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'yaml.tfstate'
    
- task: TerraformTaskV3@3
  displayName: Terrform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azure'
    
- task: TerraformTaskV3@3
  displayName: Terrform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'azure'

